namenode:
  image: bigdata/hadoop:2.8.4
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - /root/bigdata/data:/data
  environment:
    - CLUSTER_NAME=foss-cluster
    - STARTUP_SCRIPT=source /hadoop-entrypoint.sh $$@,,,source /write-config.sh $$@,,,source /namenode.sh $$@,,,
  ports:
    - "50070:50070"
    - "8020:8020"
datanode1:
  image: bigdata/hadoop:2.8.4
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - /root/bigdata/data:/data
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - CORE_CONF_hadoop_http_staticuser_user=root
    - CORE_CONF_hadoop_proxyuser_hue_hosts=*
    - CORE_CONF_hadoop_proxyuser_hue_groups=*
    - STARTUP_SCRIPT=source /hadoop-entrypoint.sh $$@,,,source /write-config.sh $$@,,,source /datanode.sh $$@,,,
resourcemanager:
  image: bigdata/hadoop:2.8.4
  hostname: resourcemanager
  container_name: resourcemanager
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_log___aggregation___enable=true
    - STARTUP_SCRIPT=source /hadoop-entrypoint.sh $$@,,,source /write-config.sh $$@,,,source /resourcemanager.sh $$@,,,
nodemanager1:
  image: bigdata/hadoop:2.8.4
  hostname: nodemanager1
  container_name: nodemanager1
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/data/hadoop/app-logs
    - STARTUP_SCRIPT=source /hadoop-entrypoint.sh $$@,,,source /write-config.sh $$@,,,source /nodemanager.sh $$@,,,

